export const USER_CREATE_URL = '/create/'
export const USER_DELETE_URL = '/delete/:id/'
export const USER_UPDATE_URL = '/update/:id/'
export const USER_DEFAULT_URL = '/'
export const LIST_USER_URL = '/list/'